<a href="https://colab.research.google.com/github/RodrigoSchneiderbr/Machine_learning/blob/main/deploy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  from sklearn import neighbors, datasets
  import pandas as pd
  import numpy as np

In [ ]:
iris = datasets.load_iris()

In [ ]:
df_iris = pd.DataFrame(data = np.c_[iris['data'], iris ['target']], columns = iris['feature_names']+['targets'])

In [ ]:
df_iris.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  targets
0                5.1               3.5  ...               0.2      0.0
1                4.9               3.0  ...               0.2      0.0
2                4.7               3.2  ...               0.2      0.0
3                4.6               3.1  ...               0.2      0.0
4                5.0               3.6  ...               0.2      0.0

[5 rows x 5 columns]

In [ ]:
x = df_iris.iloc[:, :-1].values
y = df_iris.iloc[:, 4].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 6  0  0]
 [ 0 13  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         6
         1.0       1.00      1.00      1.00        13
         2.0       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
import joblib

In [ ]:
nome_arquivo = 'modelo_knn.joblib'
joblib.dump(classifier, nome_arquivo)

['modelo_knn.joblib']

In [ ]:
scaler.mean_

array([5.81083333, 3.06      , 3.66083333, 1.14916667])

In [ ]:
scaler.var_

array([0.72163264, 0.2109    , 3.23671597, 0.59866597])

In [ ]:
import math
[math.sqrt(valores) for valores in scaler.var_]

[0.849489634362238, 0.45923850012820144, 1.799087538787988, 0.7737350788365631]

In [ ]:
!pip list -v | grep scikit-learn

scikit-learn                  1.0.2          /usr/local/lib/python3.7/dist-packages pip
