<a href="https://colab.research.google.com/github/RodrigoSchneiderbr/Machine_learning/blob/main/trabalho_pratico_modulo_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import pandas as pd
import numpy as np

In [96]:
df_classificacao = pd.read_csv("bloodtransf.csv")
df_regressao = pd.read_csv("diabetes_numeric.csv")
df_cluster = pd.read_csv("wine.csv")

Resposta 2: 748 linhas


In [14]:
df_classificacao.shape

(748, 5)

Respota 1 : 43 instancias e 3 atributos

In [17]:
df_regressao.shape


(43, 3)

Resposta 3: 178 instancias e 3 classes 



In [18]:
df_cluster.shape

(178, 14)

In [19]:
df_cluster.head()

class  Alcohol  Malic_acid  ...   Hue  OD280%2FOD315_of_diluted_wines  Proline
0      1    14.23        1.71  ...  1.04                            3.92     1065
1      1    13.20        1.78  ...  1.05                            3.40     1050
2      1    13.16        2.36  ...  1.03                            3.17     1185
3      1    14.37        1.95  ...  0.86                            3.45     1480
4      1    13.24        2.59  ...  1.04                            2.93      735

[5 rows x 14 columns]

In [20]:
df_cluster.columns

Index(['class', 'Alcohol', 'Malic_acid', 'Ash', 'Alcalinity_of_ash',
       'Magnesium', 'Total_phenols', 'Flavanoids', 'Nonflavanoid_phenols',
       'Proanthocyanins', 'Color_intensity', 'Hue',
       'OD280%2FOD315_of_diluted_wines', 'Proline'],
      dtype='object')

In [22]:
df_cluster['class'].unique()

array([1, 2, 3])

Resposta 4: Nenhuma tem dados falantes

In [23]:
df_cluster.isnull().sum()

class                             0
Alcohol                           0
Malic_acid                        0
Ash                               0
Alcalinity_of_ash                 0
Magnesium                         0
Total_phenols                     0
Flavanoids                        0
Nonflavanoid_phenols              0
Proanthocyanins                   0
Color_intensity                   0
Hue                               0
OD280%2FOD315_of_diluted_wines    0
Proline                           0
dtype: int64

In [24]:
df_classificacao.isnull().sum()

V1       0
V2       0
V3       0
V4       0
Class    0
dtype: int64

In [25]:
df_regressao.isnull().sum()

age          0
deficit      0
c_peptide    0
dtype: int64

Resposta 5: na verdade deu 0,017 mas arredondando da 0,02

In [26]:
from sklearn.model_selection import train_test_split
from sklearn import metrics 
from sklearn.linear_model import LinearRegression 
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans

Regressao linear

In [57]:
dado_saida = np.array(df_regressao['c_peptide'])
dado_entrada = np.array(df_regressao.drop('c_peptide', axis = 1))

In [29]:
train_dado_entrada_linear, test_dado_entrada_linear, train_dado_saida_linear, test_dado_saida_linear = train_test_split(dado_entrada, dado_saida, test_size = 0.37, random_state = 5762)

In [30]:
regressao = LinearRegression().fit(train_dado_entrada_linear, train_dado_saida_linear)
previsao = regressao.predict(test_dado_entrada_linear)

In [38]:
print("R2 =", round(metrics.r2_score(test_dado_saida_linear, previsao),3))

R2 = 0.017


Resposta 6: 0.53

In [37]:
print("MAE =", round(metrics.mean_absolute_error(test_dado_saida_linear, previsao),3))

MAE = 0.532


Resposta 7: 0.44

In [36]:
print("MSE =", round(metrics.mean_squared_error(test_dado_saida_linear, previsao),3))

MSE = 0.441


SVM

In [62]:
df_classificacao.head()

V1  V2     V3  V4  Class
0   2  50  12500  98      2
1   0  13   3250  28      2
2   1  16   4000  35      2
3   2  20   5000  45      2
4   1  24   6000  77      1

In [63]:
df_classificacao["Class"] = df_classificacao["Class"].map({1: 0,2: 1})

In [66]:
saida_svm = np.array(df_classificacao['Class'])
entrada_svm = np.array(df_classificacao.drop('Class', axis = 1))
train_entrada_svm, test_entrada_svm, train_saida_svm, test_saida_svm = train_test_split(entrada_svm, saida_svm, test_size = 0.37, random_state = 5762)

In [67]:
classifier = SVC(kernel = "rbf").fit(train_entrada_svm, train_saida_svm)

In [68]:
previsao_svm = classifier.predict(test_entrada_svm)

In [70]:
print("Acuracia = ", round(metrics.accuracy_score(test_saida_svm, previsao_svm),2))

Acuracia =  0.79


Resposta 8 = 0.79

In [71]:
from sklearn.metrics import classification_report, plot_confusion_matrix, plot_roc_curve

In [72]:
print(classification_report(test_saida_svm,previsao_svm))

              precision    recall  f1-score   support

           0       0.80      0.98      0.88       218
           1       0.50      0.07      0.12        59

    accuracy                           0.79       277
   macro avg       0.65      0.52      0.50       277
weighted avg       0.73      0.79      0.72       277



Resposta 9 = 0.5 e 0.07

Resposta 10 = 0.12

In [76]:
print("Precision = ", round(metrics.precision_score(test_saida_svm, previsao_svm),2))
print("Recall = ", round(metrics.recall_score(test_saida_svm, previsao_svm),2))
print("f1 = ", round(metrics.f1_score(test_saida_svm, previsao_svm),2))
print("auroc = ", round(metrics.roc_auc_score(test_saida_svm, previsao_svm),2))


Precision =  0.5
Recall =  0.07
f1 =  0.12
auroc =  0.52


Resposta 11: 0.52

KMEANS

In [97]:
df_cluster['class'] = df_cluster['class'].map({1:0,2:1,3:2})
saida_cluster = np.array(df_cluster['class'])
entrada_cluster = np.array(df_cluster.drop('class', axis = 1))
train_entrada_cluster, test_entrada_cluster, train_saida_cluster, test_saida_cluster = train_test_split(entrada_cluster, saida_cluster, test_size = 0.37, random_state = 5762)

In [98]:
cluster = KMeans(n_clusters = 3, random_state = 5762).fit(train_entrada_cluster, train_saida_cluster)

In [99]:
previsao_cluster = cluster.predict(test_entrada_cluster)

In [100]:
print("Silhueta = ", round(metrics.silhouette_score(test_entrada_cluster, previsao_cluster),2))

Silhueta =  0.6


Resposta 13 = 0.6

In [101]:
print("davies bouldin score = ", round(metrics.davies_bouldin_score(test_entrada_cluster, previsao_cluster),2))

davies bouldin score =  0.5


Resposta 14 = 0.5

In [102]:
print("mutual information = ", round(metrics.mutual_info_score(test_saida_cluster, previsao_cluster),2))

mutual information =  0.49


Resposta 15 = 0.49


In [105]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans

In [108]:
cluster = KMeans(n_clusters = 3, random_state = 5762).fit(train_entrada_cluster, train_saida_cluster)
previsao_cluster = cluster.predict(test_entrada_cluster)
print("Silhueta = ", round(metrics.silhouette_score(test_entrada_cluster, previsao_cluster),2))
print("davies bouldin score = ", round(metrics.davies_bouldin_score(test_entrada_cluster, previsao_cluster),2))
print("mutual information = ", round(metrics.mutual_info_score(test_saida_cluster, previsao_cluster),2))
print("contigencia = ", metrics.cluster.contingency_matrix(test_saida_cluster, previsao_cluster),2)

Silhueta =  0.6
davies bouldin score =  0.5
mutual information =  0.49
contigencia =  [[ 0 12  5]
 [23  0  7]
 [ 4  0 15]] 2


In [109]:
cluster = KMeans(n_clusters = 2, random_state = 5762).fit(train_entrada_cluster, train_saida_cluster)
previsao_cluster = cluster.predict(test_entrada_cluster)
print("Silhueta = ", round(metrics.silhouette_score(test_entrada_cluster, previsao_cluster),2))
print("davies bouldin score = ", round(metrics.davies_bouldin_score(test_entrada_cluster, previsao_cluster),2))
print("mutual information = ", round(metrics.mutual_info_score(test_saida_cluster, previsao_cluster),2))
print("contigencia = ", metrics.cluster.contingency_matrix(test_saida_cluster, previsao_cluster),2)

Silhueta =  0.6
davies bouldin score =  0.54
mutual information =  0.24
contigencia =  [[13  4]
 [ 2 28]
 [ 1 18]] 2


In [110]:
cluster = KMeans(n_clusters = 4, random_state = 5762).fit(train_entrada_cluster, train_saida_cluster)
previsao_cluster = cluster.predict(test_entrada_cluster)
print("Silhueta = ", round(metrics.silhouette_score(test_entrada_cluster, previsao_cluster),2))
print("davies bouldin score = ", round(metrics.davies_bouldin_score(test_entrada_cluster, previsao_cluster),2))
print("mutual information = ", round(metrics.mutual_info_score(test_saida_cluster, previsao_cluster),2))
print("contigencia = ", metrics.cluster.contingency_matrix(test_saida_cluster, previsao_cluster),2)

Silhueta =  0.53
davies bouldin score =  0.55
mutual information =  0.39
contigencia =  [[ 3  5  0  9]
 [ 8  0 20  2]
 [13  0  3  3]] 2


In [111]:
cluster = KMeans(n_clusters = 5, random_state = 5762).fit(train_entrada_cluster, train_saida_cluster)
previsao_cluster = cluster.predict(test_entrada_cluster)
print("Silhueta = ", round(metrics.silhouette_score(test_entrada_cluster, previsao_cluster),2))
print("davies bouldin score = ", round(metrics.davies_bouldin_score(test_entrada_cluster, previsao_cluster),2))
print("mutual information = ", round(metrics.mutual_info_score(test_saida_cluster, previsao_cluster),2))
print("contigencia = ", metrics.cluster.contingency_matrix(test_saida_cluster, previsao_cluster),2)

Silhueta =  0.5
davies bouldin score =  0.54
mutual information =  0.39
contigencia =  [[ 8  3  4  2  0]
 [ 2  8  0  0 20]
 [ 4 12  0  0  3]] 2


In [112]:
cluster = KMeans(n_clusters = 7, random_state = 5762).fit(train_entrada_cluster, train_saida_cluster)
previsao_cluster = cluster.predict(test_entrada_cluster)
print("Silhueta = ", round(metrics.silhouette_score(test_entrada_cluster, previsao_cluster),2))
print("davies bouldin score = ", round(metrics.davies_bouldin_score(test_entrada_cluster, previsao_cluster),2))
print("mutual information = ", round(metrics.mutual_info_score(test_saida_cluster, previsao_cluster),2))
print("contigencia = ", metrics.cluster.contingency_matrix(test_saida_cluster, previsao_cluster),2)

Silhueta =  0.55
davies bouldin score =  0.45
mutual information =  0.55
contigencia =  [[ 0  3  4  2  1  0  7]
 [15  0  3  0  3  9  0]
 [ 4  0  7  0  8  0  0]] 2
